# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["6.0.x", "8.0.x", "9.0.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start PostgreSQL with AGE extension
        run: |
          docker run --name postgres-test \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=postgres \
            -e POSTGRES_DB=agedotnet_tests \
            -p 5432:5432 \
            -d apache/age:release_PG16_1.5.0

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            if docker exec postgres-test pg_isready -U postgres -d agedotnet_tests; then
              echo "PostgreSQL is ready";
              sleep 5;
              exit 0;
            fi;
            echo "Waiting for PostgreSQL...";
            sleep 5;
          done
          echo "PostgreSQL did not become ready in time";
          exit 1;

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

        # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test with dotnet
        run: dotnet test --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      - name: Stop PostgreSQL container
        if: always()
        run: |
          docker stop postgres-test || true
          docker rm postgres-test || true
